### ISSUE TITLE
Exceeding the max request size throws unmeaning error

### ISSUE THREAD

**Issue by PhilippSpo** [sphereio/sphere-node-sdk#100]
For example if I use `productProjections` and provide a huge where query so that the request exceeds the max request size, I get this error:

```
Unhandled rejection HttpError: Parse Error
    at ProductProjectionService.BaseService._wrapResponse (/Users/psporrer/code/sphere/sphere-product-import/node_modules/sphere-node-sdk/lib/services/base.js:404:21)
    at /Users/psporrer/code/sphere/sphere-product-import/node_modules/sphere-node-sdk/lib/services/base.js:331:40
    at /Users/psporrer/code/sphere/sphere-product-import/node_modules/sphere-node-sdk/lib/connect/rest.js:201:20
    at Request._callback (/Users/psporrer/code/sphere/sphere-product-import/node_modules/sphere-node-sdk/lib/connect/rest.js:159:14)
    at self.callback (/Users/psporrer/code/sphere/sphere-product-import/node_modules/request/request.js:360:22)
    at Request.emit (events.js:107:17)
    at Request.onRequestError (/Users/psporrer/code/sphere/sphere-product-import/node_modules/request/request.js:1008:8)
    at ClientRequest.emit (events.js:107:17)
    at TLSSocket.socketOnData (_http_client.js:322:9)
    at TLSSocket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at TLSSocket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:540:20)
```

This is very bad, since it toes not tell me at all that I exceeded the request size. I don't know if this actually happens because the API is not returning anything if the request is to big, or if the request is not even sent and this error is thrown by the request lib.
Right now the solution I use, is to process product imports one by one, which obviously results in a very bad performance.
We need to check the request size when the request is built up completely (also when everything is already urlencoded) in order to throw a meaningful error.

**Comment by emmenko** [comment]
The error is coming from nginx, thus cannot be correctly parsed / mapped since it's not JSON. Nevertheless, we should handle this error yes. Simply [add a case](https://github.com/sphereio/sphere-node-sdk/blob/master/src/coffee/services/base.coffee#L579-L594) to handle `413` status codes.

PS: I'm not sure it's a good idea to manually check the request size, we can discuss this anyway.

**Comment by schleichardt** [comment]
Sometimes nginx does not return a response code at all but a html body with a description. urgs

Had the same problems in the JVM SDK.

**Comment by emmenko** [comment]
Yeah, that might also be a problem. I think @svenmueller was considering configuring nginx to return a JSON response.

**Comment by svenmueller** [comment]
Yes, errors on nginx level (e.g. request body size limit exceeded) are currently *always* returned using HTML format. We need to adjust nginx to also return error using JSON.
