### ISSUE TITLE
Error handling - cannot read property 'request' of undefined

### ISSUE THREAD

**Issue by butenkor** [sphereio/sphere-node-sdk#108]
On API error and [includeHeaders flag set](https://github.com/sphereio/sphere-node-sdk/blob/master/src/coffee/client.coffee#L145-L146) SDK will throw own error instead:
```
TypeError: Cannot read property 'request' of undefined
    at ProductService.BaseService._wrapResponse (/Users/rbutenko/dev/src/xxx-cli/node_modules/sphere-node-sdk/lib/services/base.js:382:27)
    at /Users/rbutenko/dev/src/xxx-cli/node_modules/sphere-node-sdk/lib/services/base.js:349:40
    at Request._callback (/Users/rbutenko/dev/src/xxx-cli/node_modules/sphere-node-sdk/lib/connect/rest.js:159:14)
    at self.callback (/Users/rbutenko/dev/src/xxx-cli/node_modules/sphere-node-sdk/node_modules/request/request.js:360:22)
    at Request.emit (events.js:107:17)
    at null._onTimeout (/Users/rbutenko/dev/src/xxx-cli/node_modules/sphere-node-sdk/node_modules/request/request.js:958:12)
    at Timer.listOnTimeout (timers.js:119:15)
````
as it assumes that request attribute is always provided: https://github.com/sphereio/sphere-node-sdk/blob/ee05ffd6380eb7dcb9ed2310e8762a5249ad9181/src/coffee/services/base.coffee#L535

If includeHeaders are not set SDK returns only common error message from API i.e.: "message: 'Request body does not contain valid JSON.'" and original request and error list is not available.

**Comment by butenkor** [comment]
Other examples where error returned from SDK does not contain all required information like headers, original request, endpoint and error list from API:

```
"err":{"message":"Product cannot be deleted as long as it is published in a catalog.","name":"BadRequest","stack":"BadRequest: Product cannot be deleted as long as it is published in a catalog.\n    at /Users/rbutenko/dev/src/xxx-cli/node_modules/sphere-node-sdk/lib/services/base.js:441:22\n    at ProductService.BaseService._wrapResponse (/Users/rbutenko/dev/src/xxx-cli/node_modules/sphere-node-sdk/lib/services/base.js:456:11)\n    at /Users/rbutenko/dev/src/xxx-cli/node_modules/sphere-node-sdk/lib/services/base.js:366:40\n    at Request._callback (/Users/rbutenko/dev/src/xxx-cli/node_modules/sphere-node-sdk/lib/connect/rest.js:159:14)\n    at Request.self.callback (/Users/rbutenko/dev/src/xxx-cli/node_modules/sphere-node-sdk/node_modules/request/request.js:360:22)\n    at Request.emit (events.js:110:17)\n    at Request.<anonymous> (/Users/rbutenko/dev/src/xxx-cli/node_modules/sphere-node-sdk/node_modules/request/request.js:1202:14)\n    at Request.emit (events.js:129:20)\n    at IncomingMessage.<anonymous> (/Users/rbutenko/dev/src/xxx-cli/node_modules/sphere-node-sdk/node_modules/request/request.js:1150:12)\n    at IncomingMessage.emit (events.js:129:20)\n    at _stream_readable.js:908:16\n    at process._tickCallback (node.js:355:11)","code":400},"msg":"Product cannot be deleted as long as it is published in a catalog.","time":"2016-02-11T10:20:18.939Z","v":0}
```

or on timeout there is no info which request exactly time out:
```
{"name":"xxx-cli-0.0.1","hostname":"Romans-MacBook-Pro.local","pid":28232,"level":50,"err":{"message":"ESOCKETTIMEDOUT","name":"HttpError","stack":"HttpError: ESOCKETTIMEDOUT\n    at ProductService.BaseService._wrapResponse (/Users/rbutenko/dev/src/xxx-cli/node_modules/sphere-node-sdk/lib/services/base.js:408:21)\n    at /Users/rbutenko/dev/src/xxx-cli/node_modules/sphere-node-sdk/lib/services/base.js:366:40\n    at Request._callback (/Users/rbutenko/dev/src/xxx-cli/node_modules/sphere-node-sdk/lib/connect/rest.js:159:14)\n    at self.callback (/Users/rbutenko/dev/src/xxx-cli/node_modules/sphere-node-sdk/node_modules/request/request.js:360:22)\n    at Request.emit (events.js:107:17)\n    at ClientRequest.<anonymous> (/Users/rbutenko/dev/src/xxx-cli/node_modules/sphere-node-sdk/node_modules/request/request.js:969:16)\n    at ClientRequest.g (events.js:199:16)\n    at ClientRequest.emit (events.js:104:17)\n    at TLSSocket.emitTimeout (_http_client.js:543:10)\n    at TLSSocket.g (events.js:199:16)\n    at TLSSocket.emit (events.js:104:17)\n    at TLSSocket.Socket._onTimeout (net.js:348:8)\n    at _makeTimerTimeout (timers.js:476:11)\n    at Timer.unrefTimeout (timers.js:540:5)","code":500},"msg":"ESOCKETTIMEDOUT","time":"2016-02-11T09:37:50.053Z","v":0}
```

**Comment by emmenko** [comment]
Fixed in https://github.com/sphereio/sphere-node-sdk/commit/adbc5ce7655cb7dcb8d7117f2d1f1613508b9369
