### ISSUE TITLE
Handle properly ETIMEDOUT error

### ISSUE THREAD

**Issue by lojzatran** [sphereio/sphere-node-sdk#136]
### Expected behavior
SDK should handle properly the case of ETIMEDOUT and should not fail the whole process.

### Actual behavior
TypeError is thrown and the whole process fails:
```
sphere-connect:rest error on request: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"5.79.36.218","port":443} +15s
Unhandled exception. Please handle!
TypeError: Cannot read property 'request' of undefined
    at InventoryEntryService.BaseService._wrapResponse (/Users/user/Projects/my-project-cli/node_modules/sphere-stock-import/node_modules/sphere-node-sdk/lib/services/base.js:378:27)
    at /Users/user/Projects/my-project-cli/node_modules/sphere-stock-import/node_modules/sphere-node-sdk/lib/services/base.js:331:40
    at /Users/user/Projects/my-project-cli/node_modules/sphere-stock-import/node_modules/sphere-node-sdk/lib/connect/rest.js:201:20
    at Request._callback (/Users/user/Projects/my-project-cli/node_modules/sphere-stock-import/node_modules/sphere-node-sdk/lib/connect/rest.js:159:14)
    at self.callback (/Users/user/Projects/my-project-cli/node_modules/sphere-stock-import/node_modules/sphere-node-sdk/node_modules/request/request.js:360:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/Users/user/Projects/my-project-cli/node_modules/sphere-stock-import/node_modules/sphere-node-sdk/node_modules/request/request.js:1008:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1250:8)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
Unhandled exception. Please handle!
TypeError: Cannot read property 'request' of undefined
    at InventoryEntryService.BaseService._wrapResponse (/Users/user/Projects/my-project-cli/node_modules/sphere-stock-import/node_modules/sphere-node-sdk/lib/services/base.js:378:27)
    at /Users/user/Projects/my-project-cli/node_modules/sphere-stock-import/node_modules/sphere-node-sdk/lib/services/base.js:331:40
    at /Users/user/Projects/my-project-cli/node_modules/sphere-stock-import/node_modules/sphere-node-sdk/lib/connect/rest.js:201:20
    at Request._callback (/Users/user/Projects/my-project-cli/node_modules/sphere-stock-import/node_modules/sphere-node-sdk/lib/connect/rest.js:159:14)
    at self.callback (/Users/user/Projects/my-project-cli/node_modules/sphere-stock-import/node_modules/sphere-node-sdk/node_modules/request/request.js:360:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/Users/user/Projects/my-project-cli/node_modules/sphere-stock-import/node_modules/sphere-node-sdk/node_modules/request/request.js:1008:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:259:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
    at emitErrorNT (net.js:1250:8)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
```

**Comment by emmenko** [comment]
Can you provide a PR?

**Comment by butenkor** [comment]
I think this has been fixed already. See related: https://github.com/sphereio/sphere-node-sdk/issues/140
@lojzatran Please check if it can be closed.
