### ISSUE TITLE
API error without any error details

### ISSUE THREAD

**Issue by butenkor** [sphereio/sphere-node-sdk#158]
### Expected behavior
On error should return in rejected promise request payload and server response details
### Actual behavior
On some errors it would return only:

```
{
	"name": "xxx-cli-0.13.2",
	"hostname": "xxx",
	"pid": 1,
	"level": 50,
	"error": "InternalServerError: Undefined SPHERE.IO error message\n    at /app/node_modules/sphere-node-sdk/lib/services/base.js:507:22\n    at ProductTypeService.BaseService._wrapResponse (/app/node_modules/sphere-node-sdk/lib/services/base.js:516:11)\n    at /app/node_modules/sphere-node-sdk/lib/services/base.js:358:40\n    at Request._callback (/app/node_modules/sphere-node-sdk/lib/connect/rest.js:164:14)\n    at Request.self.callback (/app/node_modules/sphere-node-sdk/node_modules/request/request.js:360:22)\n    at emitTwo (events.js:87:13)\n    at Request.emit (events.js:172:7)\n    at Request.<anonymous> (/app/node_modules/sphere-node-sdk/node_modules/request/request.js:1202:14)\n    at emitOne (events.js:82:20)\n    at Request.emit (events.js:169:7)\n    at IncomingMessage.<anonymous> (/app/node_modules/sphere-node-sdk/node_modules/request/request.js:1150:12)\n    at emitNone (events.js:72:20)\n    at IncomingMessage.emit (events.js:166:7)\n    at endReadableNT (_stream_readable.js:921:12)\n    at nextTickCallbackWith2Args (node.js:442:9)\n    at process._tickCallback (node.js:356:17)",
	"msg": "'product-import' - Unexpected error after '0d 0h 9m 20.186s'",
	"time": "2016-09-13T08:04:25.233Z",
	"v": 0
}
```

### Steps to reproduce the behavior
As error does not have any details it is hard to say when it happens and on which request/payload.

**Comment by butenkor** [comment]
@emmenko could someone please have a look?

**Comment by butenkor** [comment]
Sdk version: "sphere-node-sdk": "^1.14.0",

**Comment by PhilippSpo** [comment]
OK this seems to be an internal error:
```
InternalServerError: Undefined SPHERE.IO error message\n
at /app/node_modules/sphere-node-sdk/lib/services/base.js:507:22\n
at ProductTypeService.BaseService._wrapResponse (/app/node_modules/sphere-node-sdk/lib/services/base.js:516:11)\n
at /app/node_modules/sphere-node-sdk/lib/services/base.js:358:40\n
at Request._callback (/app/node_modules/sphere-node-sdk/lib/connect/rest.js:164:14)\n
at Request.self.callback (/app/node_modules/sphere-node-sdk/node_modules/request/request.js:360:22)\n
at emitTwo (events.js:87:13)\n
at Request.emit (events.js:172:7)\n
at Request.<anonymous> (/app/node_modules/sphere-node-sdk/node_modules/request/request.js:1202:14)\n
at emitOne (events.js:82:20)\n
at Request.emit (events.js:169:7)\n
at IncomingMessage.<anonymous> (/app/node_modules/sphere-node-sdk/node_modules/request/request.js:1150:12)\n
at emitNone (events.js:72:20)\n
at IncomingMessage.emit (events.js:166:7)\n
at endReadableNT (_stream_readable.js:921:12)\n
at nextTickCallbackWith2Args (node.js:442:9)\n
at process._tickCallback (node.js:356:17)
```

**Comment by butenkor** [comment]
Response has all the data. One has to ensure that everything is logged properly from given error data.
