### ISSUE TITLE
Extend default repeater with new error keywords

### ISSUE THREAD

**Issue by butenkor** [sphereio/sphere-node-sdk#237]
### Description
Repeater should should retry on:

```
    'connect ECONNREFUSED',
    'write ECONNRESET',
    'connect EHOSTUNREACH',
    'write EPIPE',
    'connect ECONNRESET',
    'Timed out while waiting for handshake'
```

### Expected Behavior
Should repeat on mentioned errors.

### Current Behavior
Throws an immediate exception without repeating.

More info: https://github.com/sphereio/sphere-node-sdk/blob/edfd6b2564a6daa781321495732c5543bcd4ea81/src/coffee/repeater-task-queue.coffee#L7

**Comment by junajan** [comment]
Please add also this HTTP error `write EPIPE`:
```json
{
	"name": "coeur-cli-1.10.0",
	"hostname": "ip-10-0-134-11.ec2.internal",
	"pid": 1,
	"level": 50,
	"error": "HttpError: write EPIPE\n    at ProductProjectionService.BaseService._wrapResponse (/app/node_modules/sphere-node-sdk/lib/services/base.js:461:21)\n    at /app/node_modules/sphere-node-sdk/lib/services/base.js:358:40\n    at Request._callback (/app/node_modules/sphere-node-sdk/lib/connect/rest.js:166:14)\n    at self.callback (/app/node_modules/sphere-node-sdk/node_modules/request/request.js:360:22)\n    at emitOne (events.js:90:13)\n    at Request.emit (events.js:182:7)\n    at Request.onRequestError (/app/node_modules/sphere-node-sdk/node_modules/request/request.js:1008:8)\n    at emitOne (events.js:90:13)\n    at ClientRequest.emit (events.js:182:7)\n    at TLSSocket.socketErrorListener (_http_client.js:306:9)\n    at emitOne (events.js:90:13)\n    at TLSSocket.emit (events.js:182:7)\n    at onwriteError (_stream_writable.js:312:10)\n    at onwrite (_stream_writable.js:330:5)\n    at WritableState.onwrite (_stream_writable.js:89:5)\n    at fireErrorCallbacks (net.js:454:13)\n    at TLSSocket.Socket._destroy (net.js:495:3)\n    at WriteWrap.afterWrite (net.js:785:10)",
	"msg": "'delivery-time' - Unexpected error after '0d 0h 0m 30.596s'",
	"time": "2017-08-09T03:33:50.254Z",
	"v": 0
}
```
